import java.awt.Color;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Raihan Tuhin
 */
public class Login extends javax.swing.JFrame {
    
    private Container c;
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
       
      
     clear.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
        
            tf.setText("");
            pf.setText("");
            }
        
        
        
    });
    
     
     
     
     
      submit.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
        
            
             String userName =    tf.getText();
              String password =    pf.getText();
          
               if(userName.equals("tuhin" ) && password.equals("559"))
              {
                
                  JOptionPane.showMessageDialog(null, "you are  successfully logined ");
                       dispose();
                 Dashboard frame = new Dashboard();  
                   frame.setVisible(true);
                  
            }
        
               else
              {
                  JOptionPane.showConfirmDialog(null, "invalid username or password");
              }
               
               
            } 
        
    });  
     
              } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf = new javax.swing.JTextField();
        pf = new javax.swing.JPasswordField();
        submit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 81, -1, -1));
        getContentPane().add(tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 90, -1));
        getContentPane().add(pf, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 78, 90, -1));

        submit.setBackground(new java.awt.Color(255, 255, 0));
        submit.setText("Submit");
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 141, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 0));
        jButton2.setText("creat new account");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 182, -1, -1));

        clear.setBackground(new java.awt.Color(255, 255, 51));
        clear.setText("Clear");
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 141, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setText("viwes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 182, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Raihan Tuhin\\OneDrive\\Desktop\\icon\\263157798_614533119589557_1882768965306884467_n.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 620, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        viwsroom frame = new viwsroom();
           frame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        creatnewaccount frame = new creatnewaccount();  
                   frame.setVisible(true);   
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
           Login frame = new Login();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField pf;
    private javax.swing.JButton submit;
    private javax.swing.JTextField tf;
    // End of variables declaration//GEN-END:variables
}
